// Generated by spec2c from essentials-daemon.spec.json. DO NOT EDIT.
// SPDX-License-Identifier: Apache-2.0
#define _POSIX_C_SOURCE 200809L
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <cjson/cJSON.h>
#include "vehir_lib.h"


typedef struct vehir_db vehir_db;

extern int essentials_daemon_run(vehir_db *db, int argc, char **argv);
// SPDX-License-Identifier: Apache-2.0
_Noreturn void usage(const char *prog) {
    fprintf(stderr,
        "Usage: %s\n"
        "\n"
        "Event-driven daemon: LISTENs for IPM graph changes via PostgreSQL NOTIFY (idea_changed channel), regenerates tool context block in SOUL.md under <!-- TOOLS --> marker, detects drift via SHA256 in soul_hashes, signals pain on change\n"
        "\n"
        ""
        "Output: JSON {\"ok\":true/false, ...}\n"
        "Exit:   0 = success, 1 = error, 2 = usage error\n",
        prog);
    exit(2);
}
// SPDX-License-Identifier: Apache-2.0
int main(int argc, char *argv[]) {
    if (argc > 1 && (strcmp(argv[1], "--help") == 0 || strcmp(argv[1], "-h") == 0))
        usage(argv[0]);



    vehir_db *db = NULL;


    int rc = essentials_daemon_run(db, argc, argv);




    return rc;
}
